In [2]:
import numpy as np
n = np.array([1,2,3,4,5])
print(n)

[1 2 3 4 5]


In [7]:
n = np.array([[2,3],[4,5]])
print(n)
n.shape

[[2 3]
 [4 5]]


(2, 2)

In [10]:
n = np.array([[2,3,5],[4,5,1]])
n.reshape([3,2])

array([[2, 3],
       [5, 4],
       [5, 1]])

In [11]:
n.ravel()

array([2, 3, 5, 4, 5, 1])

In [12]:
print(n)

[[2 3 5]
 [4 5 1]]


In [19]:
n = np.array([[2,3,5],[4,5,1]])
p = np.array([[9,8,7],[5,4,2]])
#sum(n,p) (axis=0)
n+p

SyntaxError: invalid syntax (295468894.py, line 3)

In [20]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
# 3 dec
import numpy as np
n1 = np.array([1,2,3,4,5])
n2 = np.array(["a","b","c"])
print(n1)
print(n2)
print(n1.ndim)
print(n2.ndim)

[1 2 3 4 5]
['a' 'b' 'c']
1
1


In [22]:
n3 = np.array(34)
print(n3.ndim)

0


In [23]:
n1 = np.array([1,2,3,4,5])
n2 = np.array([5,6,7,8])
n1.sum()

15

In [24]:
a1 = np.array([[1,2],[3,4],[5,6]])
print(a1)
a2 = np.array([[3,4],[6,7],[3,6]])
print(a2)
a1+a2

[[1 2]
 [3 4]
 [5 6]]
[[3 4]
 [6 7]
 [3 6]]


array([[ 4,  6],
       [ 9, 11],
       [ 8, 12]])

In [25]:
a1.sum(axis=1)

array([ 3,  7, 11])

In [26]:
n9 = np.array([[1,2,3],[3,4,7]])
print(n9[0,1:1])

[]


In [27]:
print(n9)
print(n9.ndim)
print(n9.shape)    #(x,y,z)

[[1 2 3]
 [3 4 7]]
2
(2, 3)


In [28]:
n1 = np.array([1,2,3])
print(n1.dtype)
print(type(n1))

int64
<class 'numpy.ndarray'>


In [29]:
print(n1.size)

3


In [30]:
n2 = np.array(["tob","bob","tom","mom"])
print(n2.dtype)

<U3


In [31]:
a = np.array([1.3,4.5,2.2], dtype=int)
b = np.array(["tob","bob","tom"])
c = np.array([1,2,3],dtype=float)
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(type(a))
print(type(b))
print(type(c))
print(a,b,c)

int64
<U3
float64
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[1 4 2] ['tob' 'bob' 'tom'] [1. 2. 3.]


## 3rd dec

In [105]:
import numpy as np

# split numpy array
# for 1d array
n = np.array([1,2,3,4,5,6])
for i in n:
    print(i)
   
rp = np.array_split(n,3)
print(rp)
for i in rp:
    print(i)
    
    
print("Splitting the 1d array")    
print(rp[0])
print(rp[1])

1
2
3
4
5
6
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
Splitting the 1d array
[1 2]
[3 4]


In [103]:
# split numpy array
# for 1d array
n1 = np.array([[1,2,3],[4,5,6],[3,5,4]])
for i in n1:
    print(i)

rp = np.array_split(n1,3)
print(rp)
    
    
print("Splitting the 2d array")    
print(rp[0])
print(rp[1])

[1 2 3]
[4 5 6]
[3 5 4]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[3, 5, 4]])]
Splitting the 2d array
[[1 2 3]]
[[4 5 6]]


In [108]:
# Search a numpy array for a value
# numpy.where() method
n2 = np.array([10,20,30,40,50,60,30])
for i in n2:
    print(i)
    
rp = np.where(n2 == 50.0)       #(array([2, 6]),) dtype shd come but is missing
print(rp)                     # comes when rp = np.where(n == 30)

10
20
30
40
50
60
30
(array([4]),)


In [49]:
# Sorting numpy arrays
# np.sort() function

n3 = np.array([13,54,75,34,97,43,11,56,73,83,53])
for i in n3:
    print(i)
    
rp = np.sort(n3)
print(rp)

13
54
75
34
97
43
11
56
73
83
53
[11 13 34 43 53 54 56 73 75 83 97]


In [51]:
# np.sort() function
# for 1d array
n4 = np.array(["Keras","Android","Tensorflow","Pandas"])
for i in n4:
    print(i)
    
rp = np.sort(n4)
print(rp)

Keras
Android
Tensorflow
Pandas
['Android' 'Keras' 'Pandas' 'Tensorflow']


In [53]:
# np.sort() function
# for 2d array
n5 = np.array([[6,3,4,1,2],[7,8,3,5,2]])
for i in n5:
    print(i)
    
rp = np.sort(n5)
print(rp)

[6 3 4 1 2]
[7 8 3 5 2]
[[1 2 3 4 6]
 [2 3 5 7 8]]


In [109]:
# Axes in numpy
n6 = np.array([[4,5,2,6,7],[2,4,2,6,6],[9,4,5,2,6]])        # Confusion
print(n6)
n6.max()

[[4 5 2 6 7]
 [2 4 2 6 6]
 [9 4 5 2 6]]


9

In [89]:
n6.max(axis=1)    # axis=1 row

array([7, 6, 9])

In [91]:
n6.max(axis=0)  

array([9, 5, 5, 6, 7])

In [90]:
n6.min(axis=0)   # axis=0 column

array([2, 4, 2, 2, 6])

In [92]:
n6.min(axis=1)

array([2, 2, 2])

In [64]:
# Intersection of numpy arrray
# Finding common elements between 2 arrays   intersect1d() method
# The resultant common elements at sorted
n7 = ([2,4,5,3,2])
n8 = ([2,4,5,7,8])
rp = np.intersect1d(n7,n8)
print(rp)

[2 4 5]


In [65]:
# What if the arrays have different elements
n7 = ([2,4,5,3,2])
n9 = ([8,9,10,7,6])

rp = np.intersect1d(n7,n9)
print(rp)

[]


In [70]:
# Difference between two array
# np.setdiff1d()
# It will leave the common elements and print the rest in the array

n7 = ([2,4,5,3,1])
n9 = ([4,5,8,7,9])

rp = np.setdiff1d(n7,n9)
print(rp)

[1 2 3]


In [72]:
n7 = ([2,4,5,3,1])
n9 = ([4,5,8,7,9])

rp = np.setdiff1d(n9,n7)
print(rp)

[7 8 9]


In [79]:
# Arithematic operations

n7 = ([2,4,5,3,1])
n9 = ([4,5,8,7,9])

rp = np.sum([n7,n9], axis=0)
print(rp)

[ 6  9 13 10 10]


In [77]:
n7 = ([2,4,5,3,1])
n9 = ([4,5,8,7,9])

rp = np.sum([n7,n9])
print(rp)

48


In [83]:
n7 = ([2,4,5,3,1])
n9 = ([4,5,8,7,9])

rp = np.subtract(n9,n7)
print(rp)

[2 1 3 4 8]


In [85]:
n7 = ([2,4,5,3,1])
n9 = ([4,5,8,7,9])

rp = np.multiply(n9,n7)
print(rp)

[ 8 20 40 21  9]


In [86]:
n7 = ([2,4,5,3,1])
n9 = ([4,5,8,7,9])

rp = np.divide(n9,n7)
print(rp)

[2.         1.25       1.6        2.33333333 9.        ]


In [111]:
n10 = np.array([1,4,2,5,7,5,6,9])
print(n10.dtype)

int64


In [112]:
print(n10.itemsize)   #8 bytes

8


In [115]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3])
print(arr.itemsize)
print(arr.dtype)
# Check bytes consumed
print("Total bytes consumed:", arr.nbytes)  # Output: 12 bytes (3 elements * 4 bytes per int32)


8
int64
Total bytes consumed: 24


#  dec 4

In [169]:
## Scaler Operation
import numpy as np
n7 = np.array ([2,4,5,3,1])
n9 = np.array([4,5,8,7,9])
n7 = n7+10;
n9 = n9+20
print(n7)
print(n9) 

[12 14 15 13 11]
[24 25 28 27 29]


In [166]:
n7 = n7+10;
n9 = n9+2;
print(n7)
print(n9) 

[32 34 35 33 31]
[10 11 14 13 15]


In [131]:
n11 = np.array([10,44,63,42,78])           # Why n9 = n9+20;......;use
n12 = np.array([43,55,70,42,12])
n11 = n11-5
n12 = n12-10
print(n11)
print(n12)

[ 5 39 58 37 73]
[33 45 60 32  2]


In [132]:
n7 = np.array ([2,4,5,3,1])
n9 = np.array([4,5,8,7,9])
n7 = n7*4
n9 = n9*6
print(n7)
print(n9) 

[ 8 16 20 12  4]
[24 30 48 42 54]


In [171]:
n7 = np.array ([2,4,5,3,1])
n9 = np.array([4,5,8,7,9])
n7 = n7%2
n9 = n9//3
print(n7)
print(n9) 

[0 0 1 1 1]
[1 1 2 2 3]


In [136]:
# Mean Median Standard Deviation of an array
n7 = np.array ([2,4,5,3,1])
n9 = np.array([4,5,8,7,9])
n7 = np.mean(n7)
n9 = np.mean(n9)
print(n7)
print(n9)

3.0
6.6


In [138]:
n7 = np.array ([2,3,4,2,4,5,7,1,1,1,3,1])
n9 = np.array([4,5,8,4,6,8,8,7,8,9,7,9])
n7 = np.median(n7)
n9 = np.median(n9)
print(n7)
print(n9)

2.5
7.5


In [140]:
# Standard deviation
# measure of the different variations or dispersion of the given values
n7 = np.array ([2,3,4,2,4,5,7,1,1,1,3,1])
n9 = np.array([4,5,8,4,6,8,8,7,8,9,7,9])
n7 = np.std(n7)
n9 = np.std(n9)
print(n7)
print(n9)

1.818118685772619
1.70579079087156


In [143]:
from numpy import random
y = random.randint(10)
print(y)

1


In [144]:
z = random.randint(10, size=3)
print(z)

[4 1 3]


In [173]:
a = random.choice([4,2,6,7,9,8,6,2], size = 3)
print(a)

[8 8 2]


In [147]:
n9 = np.array([4,5,8,7,9])
print(n9)
print(np.log2(n9))

[4 5 8 7 9]
[2.         2.32192809 3.         2.80735492 3.169925  ]


In [148]:
n9 = np.array([4,5,8,7,9])
print(n9)
print(np.log10(n9))

[4 5 8 7 9]
[0.60205999 0.69897    0.90308999 0.84509804 0.95424251]


In [150]:
a = 3
b = 12
rp = np.lcm(a,b)
print(rp)

12


In [153]:
# Greatest common divisor
a = 3
b = 12
rp = np.gcd(a,b)
print(rp)

3


In [154]:
# Changing the datatype using astype
array = np.array([1, 2, 3], dtype='int32')
float_array = array.astype('float64')
print(float_array)


[1. 2. 3.]


In [160]:
# Time datatype
date_array = np.array(['2023-12-01', '2023-12-02'], dtype='datetime64')
print(date_array)


['2023-12-01' '2023-12-02']


In [174]:
# create a python func which takes a number and returns the count of factors.
# Using the same check whether the entered number is prime or not.
def fact(n):
    y = 0
    for i in range(1,n+1):
        if n%i == 0:
            y += 1
    return y

num = int(input("Enter the number: "))
res = fact(num)
if res == 2:
    print("It is a prime.")
else:
    print("not prime")
            


Enter the number: 10
not prime


In [175]:
data = [2, 4, 6, 8, 10]
mean = sum(data) / len(data)
print(mean) 

6.0


In [176]:
# Middle value median
data = [3, 1, 4, 2, 5]
sorted_data = sorted(data)  # [1, 2, 3, 4, 5]
median = sorted_data[len(data) // 2]  
print(median) 

3


In [177]:
from statistics import mode
data = [1, 2, 2, 3, 3, 3, 4]
mode_value = mode(data)
print(mode_value) 

3


In [180]:
# Correlation
''' Measures the strength and direction of the linear relationship between two 
variables. Values range from -1 (perfect negative correlation) to 1 
(perfect positive correlation), with 0 indicating no correlation.'''

import numpy as np
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]  

correlation = np.corrcoef(x, y)[0, 1]
print(correlation)  
y = round(correlation)
print(y)

0.9999999999999999
1


In [ ]:
# Variance
'''Measures the spread of data points from the mean. A higher variance indicates
data points are more spread out; a lower variance means they are closer to the mean.'''

data = [1, 2, 3, 4, 5]
mean = sum(data) / len(data)
variance = sum((x - mean) ** 2 for x in data) / len(data)
print(variance)  # Output: 2.0


# Pandas

In [184]:
import pandas as pd
# Ways of creating dataframes
df = pd.read_csv("weather_data.csv")
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
# There are no excel version of this data
df = pd.read_excel("weather_data.xlsx","sheet 1")

In [188]:
# Using python dictionary
# Pandas DataFrame is a 2d data stucture with rows and columns.
weather_data = {
    'day':['1/1/2017','1/2/2017','1/3/2017'],
    'temperature':[32,35,28],
    'windspeed':[6,7,2],
    'event':['Rain','Sunny','Snow']
}
df = pd.DataFrame(weather_data)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [191]:
# Using tuple list
weather_data = [
    ('1/1/2017',32,6,'Rain'),
     ('1/2/2017',35,7,'Sunny'),
     ('1/3/2017',28,2,'Snow')
]
df = pd.DataFrame(weather_data, columns = ['day','temperature','windspeed','event'])
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [193]:
# 4th way
weather_data = [
    {'day':'1/1/2017', 'temperature':32, 'windspeed':6, 'event':'Rain'},
    {'day':'1/2/2017', 'temperature':35, 'windspeed':7, 'event':'Sunny'},
    {'day':'1/3/2017', 'temperature':28, 'windspeed':2, 'event':'Snow'}
]
df = pd.DataFrame(weather_data)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [195]:
df = pd.read_csv("weather_data.csv")
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
# Skipping rows
df = pd.read_csv("weather_data.csv", skiprows = 1)
print(df)

In [196]:
# Change the header, can add names aswell
df = pd.read_csv("weather_data.csv", header = None)
df

0            1          2      3
0       day  temperature  windspeed  event
1  1/1/2017           32          6   Rain
2  1/2/2017           35          7  Sunny
3  1/3/2017           28          2   Snow
4  1/4/2017           24          7   Snow
5  1/5/2017           32          4   Rain
6  1/6/2017           31          2  Sunny

In [197]:
# Fetches the rows which we mention
df = pd.read_csv("weather_data.csv", nrows = 4)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow

In [ ]:
# Syntax for changing all null or na values to NaN(not a number)
df = pd.read_csv("weather_data.csv", na_values = ['not available','n.a.', ''])
df

In [ ]:
# To change n.a to NaN from particular columns .
df = pd.read_csv("weather_data.csv", na_values = {
    'termperature':['n.a.','NaN'],
    'windspeed':[-1, n.a.]
})
df
df.to_csv('new.csv')  # for making a new file which is edited

In [ ]:
# This is to add only the columns mentioned in the new file.
df.to_csv('new.csv',columns = ['column_name','comlumn_name'])

In [ ]:
# To skip the header.
df.to_csv('new.csv', header = False)

In [ ]:
# To read the excel file
df = pd.read_excel("weather_data.csv" , 'sheet1')

In [ ]:
# Add the function that converts to nan( type of NaN is float)
def converter_cells():
    if cell = n.a.:
        return NaN
    else:
        return 'Sam Walton'
df = pd.read_excel("weather_data.csv" , 'sheet1', converters = {
    'people' : convert_cells
})
df

In [ ]:
# To create an excel sheet using pandas
with pd.ExcelWriter('stocks_weather.xlxs') as writer:
    df_stocks.to_excel(writer, sheet_name='stocks')
    df_stocks.to_excel(writer, sheet_name='weather')
    

In [204]:
df = pd.read_csv('weather_data.csv',parse_dates = ['day'])
df

day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow
3 2017-01-04           24          7   Snow
4 2017-01-05           32          4   Rain
5 2017-01-06           31          2  Sunny

In [205]:
type(df.day[0])

pandas._libs.tslibs.timestamps.Timestamp

In [208]:
# To convert day column into index
df = pd.read_csv('weather_data.csv',parse_dates = ['day'])
df.set_index('day', inplace = True)
df

temperature  windspeed  event
day                                      
2017-01-01           32          6   Rain
2017-01-02           35          7  Sunny
2017-01-03           28          2   Snow
2017-01-04           24          7   Snow
2017-01-05           32          4   Rain
2017-01-06           31          2  Sunny

In [ ]:
# to fill the places
new_df = df.fillna({
    'temperature':0,
    'windspeed':0,
    'event':'no event'
})
new_df

In [ ]:
# instead of 0 it will print the value of the previous element
new_df = df.fillna(method ='ffill')
new_df

In [ ]:
# instead of 0 it will print the value of the element after it
# column indicates that the element is taken from the next element column-wise
# limit only makes this happen those many times, in this case once
new_df = df.fillna(method ='bfill',axis='column',limit = 1)
new_df

In [ ]:
# This is to drop the column which contains no values
new_df = df.dropna(how = 'all')
new_df

In [ ]:
# Handling missing data
''' First indexing, then fillna with 0, then can use methods like ffill(Forward value).
bfill method is for backward value, axis provides with column or row option.

In [ ]:
# To handle unique data
''' We can use replace( , )'''
new_df = df.replace('snow',np.NaN)    #Value you want to replace and with what value
new_df

In [ ]:
new_df = df.replace({
    'temperature':value
    'windspeed':value
    'event':value
},np.NaN)    #Value you want to replace and with what value
new_df

In [214]:
df = pd.DataFrame({
    'score': ['exceptional','average','good','poor','average','exceptional'],
    'students': ['rob','maya','parvathi','tom','julian','erica']
})
df

score  students
0  exceptional       rob
1      average      maya
2         good  parvathi
3         poor       tom
4      average    julian
5  exceptional     erica

In [215]:
df_new = df.replace(['poor','average','good','exceptional'],[1,2,3,4])
df_new

/var/folders/h1/n_brrnn95rbgjntwcswbttnw0000gn/T/ipykernel_57935/4257800819.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_new = df.replace(['poor','average','good','exceptional'],[1,2,3,4])


score  students
0      4       rob
1      2      maya
2      3  parvathi
3      1       tom
4      2    julian
5      4     erica

In [219]:
df_new['score']

0    4
1    2
2    3
3    1
4    2
5    4
Name: score, dtype: int64